### ISSUE TITLE
View Page STUDENT

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#10]
As an Student 
I want a View page
So that I can view overall books.

- [x] FrontEnd development of Viewpage @sumitkaji 
- [ ] BackEnd development of Viewpage @Prasuna-Pokharel

**Comment by sumitkaji** [comment]
![student](https://user-images.githubusercontent.com/81735853/118349624-755ea180-b571-11eb-9f73-321d0453ee96.png)
this is how student dashboard looks like so that they can view overall books.
