### ISSUE TITLE
Update Page 

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#11]
As an administrator 
I want an update page
So that I can update reserved books.

- [x] FrontEnd development of Viewpage @sumitkaji 
- [ ] BackEnd development of Viewpage @Prasuna-Pokharel

**Comment by sumitkaji** [comment]
![update](https://user-images.githubusercontent.com/81735853/118349699-eaca7200-b571-11eb-8d1b-9e31d2c51a32.png)
this is how update page looks like so that admin can update reserved books
