### ISSUE TITLE
Student Reserve Book

### ISSUE THREAD

**Issue by Supriya47** [Supriya47/LibraryManagementSystem-Frontend-#13]
As a student 
I want a reserve button
So that I can reserve available books.

- [ ] Frontend development of reserve book @sumitkaji 
- [ ] Backend development of reserve book @Janak-Bhatta-developer

**Comment by Janak-Bhatta-developer** [comment]
![Reserve](https://user-images.githubusercontent.com/80842107/118239570-abd8e580-b4b9-11eb-9d69-b65be3c2dccf.JPG)
Reserve button Done!!

**Comment by sumitkaji** [comment]
![student](https://user-images.githubusercontent.com/81735853/118362159-0a7f8b80-b5ae-11eb-8ba6-cc1380d67581.png)
student can reserve book
