### ISSUE TITLE
Reservation Access

### ISSUE THREAD

**Issue by Supriya47** [Supriya47/LibraryManagementSystem-Frontend-#14]
As an administrator
I want to  give access 
So that if multiple students try to reserve one book at a time I could choose whom to lend the books.

- [ ] Frontend development of reservation access @sumitkaji 
- [ ] Backend development of reservation access @Janak-Bhatta-developer

**Comment by Janak-Bhatta-developer** [comment]
![Assign reservation](https://user-images.githubusercontent.com/80842107/118245364-6d92f480-b4c0-11eb-8365-f268d4229ee9.JPG)
Reservation Access done !!
