### ISSUE TITLE
Admin username and password in student login

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#18]
### Bug Summary:
Instead of receiving an error or warning message, you will be redirected to the admin dashboard if you use the admin username and password on the student login page.

### Steps to Reproduce:
1. Click on student and click on login
2. Enter Admin Username: Admin
3. Enter Admin Password: Admin
4. Click on SignUp Button.

![i3](https://user-images.githubusercontent.com/80934693/118019603-e25b1700-b378-11eb-987e-4be6e10a407d.png)

- [ ]  @Janak-Bhatta-developer

**Comment by Janak-Bhatta-developer** [comment]
![admin page solved](https://user-images.githubusercontent.com/80842107/118238600-7089e700-b4b8-11eb-9031-95a5d7358eb6.JPG)
Admin issue solved!!
