### ISSUE TITLE
Missing footer

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#21]
Include footer in login page. 

**Attachment:**
![issue1](https://user-images.githubusercontent.com/80934693/118268338-fb7cd880-b4dc-11eb-818b-b2a20a7274c4.png)

**Comment by sumitkaji** [comment]
![issue 4](https://user-images.githubusercontent.com/81735853/118351528-4699f880-b57c-11eb-848b-9c067089e012.png)
missing footer in login page fixed.
