### ISSUE TITLE
Align Reserve Button

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#22]
It would look better if the reserve button was align in  home page.

**Attachment:**
![sumit](https://user-images.githubusercontent.com/80934693/118297246-9c7b8b80-b4fd-11eb-9d03-4c5f71f2de0c.png)

- [x]  @sumitkaji

**Comment by sumitkaji** [comment]
![issue 3](https://user-images.githubusercontent.com/81735853/118351226-78aa5b00-b57a-11eb-8d7a-c170d3822792.png)
issue fixed button are in align position
