### ISSUE TITLE
Login page cursor

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#23]
In a button, the default cursor is unattractive. It would be more attractive and pleasing if the cursor was a pointer or if the buttons on the login page had a hover impact.

**Attachment:**
![sumit2](https://user-images.githubusercontent.com/80934693/118298799-a900e380-b4ff-11eb-9937-5c2dde9d26a1.png)

- [ ]  @sumitkaji

**Comment by sumitkaji** [comment]
![issue 2](https://user-images.githubusercontent.com/81735853/118351061-7398dc00-b579-11eb-95d0-705299a7cc39.png)
issue fixed of curser pointer in login page
