### ISSUE TITLE
Button text size

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#25]
It would be preferable if the button text was included inside the button.

**Attachment:**
![adminissue](https://user-images.githubusercontent.com/80934693/118301068-6260b880-b502-11eb-9e3a-0cc95f0c2499.png)

- [ ] @sumitkaji

**Comment by sumitkaji** [comment]
![issue1](https://user-images.githubusercontent.com/81735853/118348429-f7e36300-b569-11eb-964c-73e491f40583.png)

Fixed button text size bug
