### ISSUE TITLE
Reserve button is not working properly

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#29]
### Bug Summary:
When student click on reserve button request is not sent to admin
### Steps to Reproduce:
1. Click on Student and click on login and Enter username and password and login to Student dashboard.
2. Choose book and click on reserve

### Attachment
![bugi_issue1](https://user-images.githubusercontent.com/80934693/118369678-03fc0e80-b5c4-11eb-9b6c-b813232e91c2.jpg)

- [ ]  @Janak-Bhatta-developer

**Comment by Janak-Bhatta-developer** [comment]
![b3](https://user-images.githubusercontent.com/80842107/118386281-1e6ed000-b636-11eb-8238-2dd821de7a54.JPG)
Issue solved!!
