### ISSUE TITLE
Unwanted cancle Reserve button

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#30]
### Bug Summary:
If student open student dashboard view book page there is unwanted cancel reserve button.

### Attachment:
![librayrissue](https://user-images.githubusercontent.com/80934693/118369948-2b9fa680-b5c5-11eb-99ab-5d17880d25af.jpg)

- [ ]  @Janak-Bhatta-developer

**Comment by Janak-Bhatta-developer** [comment]
![Reserve](https://user-images.githubusercontent.com/80842107/118386221-aa342c80-b635-11eb-9bad-6dea4af996b1.JPG)
Issue solved !! cancel button removed successfully.
