### ISSUE TITLE
Invalid DataType.

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#31]
### Bug Summary:
No error or warning message appears on the screen when users enter invalid Enrollment data.
Steps to Reproduce:
1. Click on student and click on signup 
2. Enter First name: sumit
3. Enter Last name: thapa
4. Enter Existing Username: sumit1
5. Enter Password: SumitLMS
6. Enter Enrollment: XYZ	 
7. Enter Branch: IT
8. Click on SignUp Button.

### Attachment:
![admin](https://user-images.githubusercontent.com/80934693/118371867-39a5f500-b5ce-11eb-8a56-e997a36ae383.png)

**Comment by Prasuna-Pokharel** [comment]
**I have solved the error, now I cannot enter a character in the field**
![2](https://user-images.githubusercontent.com/80803470/118372322-cd78c080-b5d0-11eb-9012-a69c44325585.png)
