### ISSUE TITLE
Admin Dashboard 

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#7]
As an administrator
I want an admin dashboard
So that I can add, delete, update, and view books.

- [ ] interface design of Admin dashboard
- [x] backend development of Admin dashboard

**Comment by Prasuna-Pokharel** [comment]
**As in this sprint my work was to Add book only so I have Only done ADD books in Dashboard  and worked on adding books in database**
![Admin Dashboard](https://user-images.githubusercontent.com/80803470/114860858-3ae7d480-9e0c-11eb-9b28-675a4e72df63.jpg)
![Add Book](https://user-images.githubusercontent.com/80803470/114860865-3cb19800-9e0c-11eb-94b0-12725b8b606c.jpg)
![Book Added Sucessfully](https://user-images.githubusercontent.com/80803470/114860862-3cb19800-9e0c-11eb-9954-0e567aed3a4b.jpg)
![Adding book Database](https://user-images.githubusercontent.com/80803470/114860869-3d4a2e80-9e0c-11eb-889f-1a363189fbe7.jpg)

**Comment by Biraj18** [comment]
Thats good prasuna @sumitkaji do you have completed your work?

**Comment by sumitkaji** [comment]
![admindashboard](https://user-images.githubusercontent.com/81735853/118349451-72af7c80-b570-11eb-9dc1-e65d3f9f37d4.png)
This is how admin dashboard looks like so that, admin can add, delete, update, and view books.
