### ISSUE TITLE
View Page ADMIN

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem-Frontend-#9]
As an administrator 
I want a View page
So that I can view overall books.

- [x] FrontEnd development of viewpage ADMIN@sumitkaji 
- [ ] BackEnd development of viewpage ADMIN @Prasuna-Pokharel

**Comment by sumitkaji** [comment]
![admin](https://user-images.githubusercontent.com/81735853/118349512-dcc82180-b570-11eb-8136-4b37a1513363.png)
this is admin dashboard 
in this page admin can view overall books
